# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ychen428/Desktop/semi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ychen428/Desktop/semi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ychen428/Desktop/semi/CMakeFiles /home/ychen428/Desktop/semi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ychen428/Desktop/semi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named semi++

# Build rule for target.
semi++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 semi++
.PHONY : semi++

# fast build rule for target.
semi++/fast:
	$(MAKE) -f CMakeFiles/semi++.dir/build.make CMakeFiles/semi++.dir/build
.PHONY : semi++/fast

#=============================================================================
# Target rules for targets named io

# Build rule for target.
io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 io
.PHONY : io

# fast build rule for target.
io/fast:
	$(MAKE) -f src/io/CMakeFiles/io.dir/build.make src/io/CMakeFiles/io.dir/build
.PHONY : io/fast

#=============================================================================
# Target rules for targets named libsemi

# Build rule for target.
libsemi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libsemi
.PHONY : libsemi

# fast build rule for target.
libsemi/fast:
	$(MAKE) -f src/semi/CMakeFiles/libsemi.dir/build.make src/semi/CMakeFiles/libsemi.dir/build
.PHONY : libsemi/fast

#=============================================================================
# Target rules for targets named arma_test

# Build rule for target.
arma_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arma_test
.PHONY : arma_test

# fast build rule for target.
arma_test/fast:
	$(MAKE) -f tests/CMakeFiles/arma_test.dir/build.make tests/CMakeFiles/arma_test.dir/build
.PHONY : arma_test/fast

#=============================================================================
# Target rules for targets named io_utils_test

# Build rule for target.
io_utils_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 io_utils_test
.PHONY : io_utils_test

# fast build rule for target.
io_utils_test/fast:
	$(MAKE) -f tests/CMakeFiles/io_utils_test.dir/build.make tests/CMakeFiles/io_utils_test.dir/build
.PHONY : io_utils_test/fast

#=============================================================================
# Target rules for targets named semi_test

# Build rule for target.
semi_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 semi_test
.PHONY : semi_test

# fast build rule for target.
semi_test/fast:
	$(MAKE) -f tests/CMakeFiles/semi_test.dir/build.make tests/CMakeFiles/semi_test.dir/build
.PHONY : semi_test/fast

#=============================================================================
# Target rules for targets named framework_test

# Build rule for target.
framework_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 framework_test
.PHONY : framework_test

# fast build rule for target.
framework_test/fast:
	$(MAKE) -f tests/CMakeFiles/framework_test.dir/build.make tests/CMakeFiles/framework_test.dir/build
.PHONY : framework_test/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/semi++.dir/build.make CMakeFiles/semi++.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/semi++.dir/build.make CMakeFiles/semi++.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/semi++.dir/build.make CMakeFiles/semi++.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... semi++"
	@echo "... io"
	@echo "... libsemi"
	@echo "... arma_test"
	@echo "... io_utils_test"
	@echo "... semi_test"
	@echo "... framework_test"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

